### ISSUE TITLE
Problem of running example

### ISSUE THREAD

**Issue by yeahq** [mattjj/pyhsmm-factorial#1]
I try to run the updated factorial example inside pyhsmm/plugins and I got this exception: 

```
Traceback (most recent call last):
  File "pyhsmm\plugins\factorial\example.py", line 19, in <module>
    mu=0,sigmasq=0.01),
TypeError: __init__() got an unexpected keyword argument 'mu'
```

I think there might be some miss match of the interface version. 

My python:  Python 2.7.3 -- EPD 7.3-2 (64-bit)

**pyhsmm version**:

```
commit 8e35811bd9b92d0de8f30c880a23fc6a4bb9f4a2
Author: Matthew Johnson <mattjj@csail.mit.edu>
Date:   Sat Feb 2 17:28:34 2013 -0500
```

**factorial version**: 

```
commit 31a3c1acd838ce78a2e099fdd357018ecf90f42b
Author: Matthew Johnson <mattjj@csail.mit.edu>
Date:   Sat Feb 2 17:35:21 2013 -0500
```

**Comment by mattjj** [comment]
The issue is an outdated version of the pybasicbayes submodule of pyhsmm. If you cd into pyhsmm/basic/pybasicbayes the commit should be 461ab8b.

A 'git pull' and 'git submodule update' in pyhsmm should update it to that commit (I just made sure the most recent pybasicbayes is in pyhsmm). Let me know if it still doesn't work.

**Comment by yeahq** [comment]
I can run the example pretty well now. Thank you.

2013/2/2 Matthew Johnson notifications@github.com
