### ISSUE TITLE
TypeError: __init__() got multiple values for keyword argument 'mu'

### ISSUE THREAD

**Issue by liubenyuan** [mattjj/pyhsmm-factorial#3]
Hi,

I run into the following error when I pull the pyhsmm and pyhsmm-factorial today, any solutions ? 

```
  ---------------------------------------------------------------------------
  TypeError                                 Traceback (most recent call last)
  /usr/lib/python2.7/site-packages/IPython/utils/py3compat.py in execfile(fname, *where)
      202             else:
      203                 filename = fname
  --> 204             __builtin__.execfile(filename, *where)

  /home/postgres/kaggle/python_mod/pyhsmm/plugins/factorial/example.py in <module>()
       17         pyhsmm.basic.distributions.ScalarGaussianNonconjNIX(
       18             None,None,None,None, # no hyperparameters since we won't resample
  ---> 19             mu=0,sigmasq=0.01),
       20         pyhsmm.basic.distributions.ScalarGaussianNonconjNIX(
       21             None,None,None,None,

  TypeError: __init__() got multiple values for keyword argument 'mu'
```

**Comment by mattjj** [comment]
Sorry, I totally broke factorial models when I rewrote parts of pyhsmm and pybasicbayes recently and I haven't gotten around to updating the factorial models. 

The short term solution is to check out a compatible older version of pyhsmm. I can find a working commit to use when I get back to a computer later today. A version from 3-5 months ago should work. 

The long term solution is to fix the factorial models. They only broke because I was in a rush and didn't apply some updates to them, so it shouldn't be too hard, but I don't remember what they need done.

I'll update you on any progress.

**Comment by liubenyuan** [comment]
Thanks !

I donnot know if it is off topic. I am learning your JMLR paper and try to implement the pyhsmm-factorial on two dimensional time sequances. i.e., at each time point t, a vector of observation is obtained. I totally buried in your code these days and do not know where is a good start to hacking around . any hints ?

**Comment by mattjj** [comment]
Here are some preliminary thoughts:
- The code is very object-oriented, especially the factorial models. I came to that design first by writing [pybasicbayes](https://www.github.com/mattjj/pybasicbayes), then extending the design to pyhsmm, and then finally extending it to the factorial models. It might be helpful to understand the object models in that sequence, since they build on each other. (Of course, please tell me if you think the design is bad or confusing!)
- Broadly speaking, a [Factorial model](https://github.com/mattjj/pyhsmm-factorial/blob/master/models.py#L14) is the wrapper that contains several [Component models](https://github.com/mattjj/pyhsmm-factorial/blob/master/models.py#L86), where each component models a particular latent component (e.g. one for a refrigerator, one for a microwave, etc.). Similarly the [state sequence for a Factorial model](https://github.com/mattjj/pyhsmm-factorial/blob/master/internals/states.py#L12) wraps several individual [component state sequences](https://github.com/mattjj/pyhsmm-factorial/blob/master/internals/states.py#L148) (e.g. a component state sequence might be a refrigerator state sequence, and another might be a microwave state sequence; the factorial state sequence just includes all component state sequences). Component models are really just HSMMs. There are a lot of pointers going around because component models need to look at all the data.
- The component state sequences are sampled one at a time (conditioned on the other component state sequences and all components' parameters), though the component emissions are marginalized out in that step (since, conditioned on other state sequences, the data likelihood is just Gaussian). [Adding extra noise](https://github.com/mattjj/pyhsmm-factorial/blob/master/example.py#L75) (i.e. annealing) is important to allow the sampler to explore.
- The factorial code is specialized to 1D because of the application I was using and because it simplified a likelihood calculation (there's a specialized Cholesky downdate routine used [where the component emissions are sampled](https://github.com/mattjj/pyhsmm-factorial/blob/master/internals/states.py#L109) which relies on 1D emissions with diagonal (uncorrelated) noise), but in principle it's just sampling a joint Gaussian conditioned on the states (which determine the covariance matrix).
- There are [some places where abstractions are broken](https://github.com/mattjj/pyhsmm-factorial/blob/master/models.py#L90) which were meant to keep memory contiguous and slightly reduce the number of re-allocations, but in retrospect I think that was unnecessary and relatively ineffective optimization.

Let me know if you have specific questions. I have trouble reading other peoples' complex code, so you may end up deciding that it'd be easier for you to write your own than use this factorial library. In that case, you may still be able to use parts of pyhsmm.

**Comment by mattjj** [comment]
Okay, the temporary solution is to check out pyhsmm commit af79471, which I branched as working-factorial. You probably want to just start fresh with a new clone, so you should be able to do these things:

``` bash
git clone -b working-factorial https://github.com/mattjj/pyhsmm.git
cd pyhsmm
git submodule update --init --recursive
git clone https://github.com/mattjj/pyhsmm-factorial.git ./plugins/factorial

# test example, making sure the correct pyhsmm is used
cd ..
export PYTHONPATH=.:$PYTHONPATH # if you use bash/zsh
python pyhsmm/plugins/factorial/example.py
```

Hopefully that works! Let me know if you get any errors.

**Comment by mattjj** [comment]
Btw, the example often samples negative emissions because I only used conjugate priors for convenience. Luckily that wasn't an issue in the real data experiment from the paper (I don't remember using any tricks to get around it), but it would be much smarter to use a nonconjugate prior that only allowed nonnegative emission mean parameters (though resampling those parameters would be a bit less convenient). That may not be an issue for you, but for power disaggregation it's probably a really important constraint.

**Comment by liubenyuan** [comment]
Yeah, It worked. I do a small modification in pyhsmm/plugins/factorial/internal/state.py, and point the location of Eigen3 to 

```
include_dirs=['../../deps/Eigen3']
```

I will firstly start reading you pybasicbayes code! Thanks~~

**Comment by mattjj** [comment]
I pushed that change to `include_dirs` into 413b402. I'm going to close this issue since it's functional, but I'll open another about making it work with more recent versions of pyhsmm.
